//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change....
        /// </summary>
        public static string ChangeTask {
            get {
                return ResourceManager.GetString("ChangeTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task memo:.
        /// </summary>
        public static string ChangeTask_TaskMemo {
            get {
                return ResourceManager.GetString("ChangeTask_TaskMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task project:.
        /// </summary>
        public static string ChangeTask_TaskProject {
            get {
                return ResourceManager.GetString("ChangeTask_TaskProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change current task.
        /// </summary>
        public static string ChangeTaskTitle {
            get {
                return ResourceManager.GetString("ChangeTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current task.
        /// </summary>
        public static string CurrentTaskHeader {
            get {
                return ResourceManager.GetString("CurrentTaskHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics_Header {
            get {
                return ResourceManager.GetString("Statistics_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month.
        /// </summary>
        public static string Statistics_ThisMonth {
            get {
                return ResourceManager.GetString("Statistics_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week.
        /// </summary>
        public static string Statistics_ThisWeek {
            get {
                return ResourceManager.GetString("Statistics_ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StopButton {
            get {
                return ResourceManager.GetString("StopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TimeRegistrationError_Caption {
            get {
                return ResourceManager.GetString("TimeRegistrationError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when trying to save time information.
        /// </summary>
        public static string TimeRegistrationError_Message {
            get {
                return ResourceManager.GetString("TimeRegistrationError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time tracking is OFF.
        /// </summary>
        public static string TimeTrackingOff {
            get {
                return ResourceManager.GetString("TimeTrackingOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time tracking is ON.
        /// </summary>
        public static string TimeTrackingOn {
            get {
                return ResourceManager.GetString("TimeTrackingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time tracking.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
